name: ncHtTerrain
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - blosc=1.21.6=hf7d4471_0
  - bottleneck=1.4.2=py313hf0014fa_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.9.9=h06a4308_0
  - certifi=2025.10.5=py313h06a4308_0
  - cftime=1.6.4=py313hf0014fa_0
  - expat=2.7.1=h6a678d5_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.14.5=h2b7332f_2
  - icu=73.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jpeg=9f=h5ce9db8_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libaec=1.1.3=h6a678d5_0
  - libcurl=8.15.0=hc1efc7f_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libnetcdf=4.9.3=h71f9cbe_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzip=1.8.0=h6ac8c49_1
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py313hacdc0fc_0
  - mkl_fft=1.3.11=py313hacdc0fc_1
  - mkl_random=1.2.8=py313h8928b4f_1
  - ncurses=6.5=h7934f7d_0
  - netcdf4=1.7.2=py313hbe59ae5_2
  - numexpr=2.11.0=py313h41d4191_1
  - numpy=2.3.3=py313h720eef7_0
  - numpy-base=2.3.3=py313h95072fd_0
  - openssl=3.0.18=hd6dcaed_0
  - pandas=2.3.3=py313h23c847b_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.13.7=h7e8bc2b_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=1_cp313
  - pytz=2025.2=py313h06a4308_0
  - readline=8.3=hc2a1206_0
  - scipy=1.16.2=py313h33bc11c_0
  - setuptools=72.1.0=py313h06a4308_0
  - six=1.17.0=py313h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
prefix: /h/eol/srunkel/.conda/envs/ncUtils
